# Helm values for multi-tenant PolicyCortex deployment

global:
  tenants:
    - name: default
      namespace: tenant-default
      tier: free
      quotas:
        maxRequests: 1000
        maxStorage: 1Gi
        maxCompute: 100m
    - name: alpha
      namespace: tenant-alpha
      tier: pro
      quotas:
        maxRequests: 10000
        maxStorage: 10Gi
        maxCompute: 500m
    - name: beta
      namespace: tenant-beta
      tier: pro
      quotas:
        maxRequests: 10000
        maxStorage: 10Gi
        maxCompute: 500m
    - name: enterprise
      namespace: tenant-enterprise
      tier: enterprise
      quotas:
        maxRequests: unlimited
        maxStorage: 100Gi
        maxCompute: 2000m

# Per-tenant resource quotas
resourceQuotas:
  free:
    limits.cpu: "2"
    limits.memory: "4Gi"
    requests.cpu: "500m"
    requests.memory: "1Gi"
    persistentvolumeclaims: "5"
    services.loadbalancers: "0"
  pro:
    limits.cpu: "8"
    limits.memory: "16Gi"
    requests.cpu: "2"
    requests.memory: "4Gi"
    persistentvolumeclaims: "20"
    services.loadbalancers: "2"
  enterprise:
    limits.cpu: "32"
    limits.memory: "64Gi"
    requests.cpu: "8"
    requests.memory: "16Gi"
    persistentvolumeclaims: "100"
    services.loadbalancers: "10"

# Tenant-specific service configurations
services:
  api:
    replicasPerTenant:
      free: 1
      pro: 2
      enterprise: 3
    resources:
      free:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      pro:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi
      enterprise:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi

  database:
    storagePerTenant:
      free: 1Gi
      pro: 10Gi
      enterprise: 100Gi
    backupEnabled:
      free: false
      pro: true
      enterprise: true
    backupSchedule:
      pro: "0 2 * * *"  # Daily at 2 AM
      enterprise: "0 */6 * * *"  # Every 6 hours

# Security policies per tier
security:
  encryption:
    free:
      atRest: false
      inTransit: true
    pro:
      atRest: true
      inTransit: true
    enterprise:
      atRest: true
      inTransit: true
      keyRotation: true
  
  authentication:
    free:
      methods: ["basic"]
    pro:
      methods: ["oauth2", "saml"]
    enterprise:
      methods: ["oauth2", "saml", "mtls", "jwt"]
      mfa: required

# Observability settings
monitoring:
  metrics:
    retention:
      free: "7d"
      pro: "30d"
      enterprise: "90d"
  logs:
    retention:
      free: "3d"
      pro: "14d"
      enterprise: "30d"
  tracing:
    enabled:
      free: false
      pro: true
      enterprise: true
    samplingRate:
      pro: 0.1
      enterprise: 1.0