# Istio Base Configuration for PolicyCortex
global:
  istioNamespace: istio-system
  defaultResources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  proxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  mtls:
    enabled: true
    auto: true

# Enable telemetry for observability
telemetry:
  v2:
    enabled: true
    prometheus:
      configOverride:
        inboundSidecar:
          disable_host_header_fallback: true
        outboundSidecar:
          disable_host_header_fallback: true
        gateway:
          disable_host_header_fallback: true

# Security settings
pilot:
  autoscaleEnabled: true
  autoscaleMin: 2
  autoscaleMax: 5
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  env:
    PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
    PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY: true