# Rust formatting configuration for PolicyCortex
# Compatible with stable Rust channel

# Edition and version
edition = "2021"

# Basic formatting
max_width = 100
tab_spaces = 4

# Function and method formatting
fn_params_layout = "Tall"

# Expression formatting  
chain_width = 60
single_line_if_else_max_width = 50
force_explicit_abi = true

# Other stable formatting options
remove_nested_parens = true
use_small_heuristics = "Default"
reorder_imports = true

# Match formatting
match_block_trailing_comma = false