server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: policycortex
    external_labels:
      cluster: policycortex
      environment: production

scrape_configs:
  # Docker containers logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            docker:
              container_id: container_id
      - regex:
          expression: '^(?P<container_id>[a-f0-9]{12})'
      - labels:
          container_id:
      - timestamp:
          format: RFC3339Nano
          source: time
      - output:
          source: output

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    
  # PolicyCortex application logs
  - job_name: policycortex-core
    static_configs:
      - targets:
          - localhost
        labels:
          job: policycortex-core
          service: core-api
          __path__: /var/log/policycortex/core/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z?) \[(?P<level>\w+)\] (?P<message>.*)'
      - labels:
          level:
      - timestamp:
          format: RFC3339
          source: timestamp
          
  - job_name: policycortex-frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: policycortex-frontend
          service: frontend
          __path__: /var/log/policycortex/frontend/*.log
          
  - job_name: policycortex-api-gateway
    static_configs:
      - targets:
          - localhost
        labels:
          job: policycortex-api-gateway
          service: api-gateway
          __path__: /var/log/policycortex/api-gateway/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:
          trace_id:
      - timestamp:
          format: RFC3339
          source: timestamp