apiVersion: v1
kind: ConfigMap
metadata:
  name: policycortex-config
  namespace: policycortex-prod
data:
  NODE_ENV: "production"
  ENVIRONMENT: "prod"
  NEXT_PUBLIC_APP_URL: "https://policycortex.azure.com"
  NEXT_PUBLIC_API_URL: "https://api.policycortex.azure.com"
  NEXT_PUBLIC_GRAPHQL_URL: "https://graphql.policycortex.azure.com"
  AZURE_TENANT_ID: "e1f3e196-aa55-4709-9c55-0e334c0b444f"
  AZURE_CLIENT_ID: "232c44f7-d0cf-4825-a9b5-beba9f587ffb"
  AZURE_SUBSCRIPTION_ID: "6dc7cfa2-0332-4740-98b6-bac9f1a23de9"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/policycortex_prod"
  REDIS_URL: "redis://redis-service:6379"
  CORS_ORIGIN: "https://policycortex.azure.com"