name: 'Import Resource Groups'
description: 'Import existing Azure resource groups into Terraform state'
inputs:
  environment:
    description: 'Environment name (dev, staging, prod)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Import Resource Groups
      shell: bash
      run: |
        echo "Checking and importing existing resource groups for ${{ inputs.environment }}..."
        
        # Get subscription ID
        SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        
        # Check and import Network Resource Group
        NETWORK_RG="rg-policycortex-network-${{ inputs.environment }}"
        if az group show --name "$NETWORK_RG" &>/dev/null; then
          echo "Resource group $NETWORK_RG exists in Azure"
          if ! terraform state show azurerm_resource_group.network &>/dev/null; then
            echo "Importing $NETWORK_RG into Terraform state..."
            terraform import azurerm_resource_group.network "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$NETWORK_RG" || {
              echo "Failed to import $NETWORK_RG - it may already be in state or not exist"
            }
          else
            echo "$NETWORK_RG already in Terraform state"
          fi
        else
          echo "Resource group $NETWORK_RG does not exist in Azure - will be created"
        fi
        
        # Check and import Application Resource Group
        APP_RG="rg-policycortex-app-${{ inputs.environment }}"
        if az group show --name "$APP_RG" &>/dev/null; then
          echo "Resource group $APP_RG exists in Azure"
          if ! terraform state show azurerm_resource_group.app &>/dev/null; then
            echo "Importing $APP_RG into Terraform state..."
            terraform import azurerm_resource_group.app "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$APP_RG" || {
              echo "Failed to import $APP_RG - it may already be in state or not exist"
            }
          else
            echo "$APP_RG already in Terraform state"
          fi
        else
          echo "Resource group $APP_RG does not exist in Azure - will be created"
        fi 