[package]
name = "policycortex-core"
version = "2.0.0"
edition = "2021"
authors = ["AeoliTech"]
description = "PolicyCortex v2 - AI-Powered Azure Governance Platform"

[dependencies]
# Web Framework
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "compression"] }
hyper = "1.0"

# Async Runtime
tokio = { version = "1", features = ["full"] }
futures = "0.3"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
sea-orm = { version = "0.12", features = ["sqlx-postgres", "runtime-tokio-rustls"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# GraphQL
async-graphql = "7.0"
async-graphql-axum = "7.0"

# Event Sourcing
eventstore = "3.0"

# Cache
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }

# Authentication
jsonwebtoken = "9.2"
argon2 = "0.5"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
config = "0.13"
dotenvy = "0.15"

# UUID
uuid = { version = "1.6", features = ["v4", "serde"] }

# Date/Time
chrono = { version = "0.4", features = ["serde"] }

# Error Handling
thiserror = "1.0"
anyhow = "1.0"

# Blockchain
sha2 = "0.10"
hex = "0.4"

# Quantum-resistant crypto
pqcrypto-kyber = "0.7"
pqcrypto-dilithium = "0.4"

[dev-dependencies]
mockall = "0.12"
proptest = "1.4"
criterion = "0.5"

[[bench]]
name = "performance"
harness = false