# Prometheus Configuration for ML Monitoring
# Patent #4: Predictive Policy Compliance Engine

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'policycortex-ml'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files
rule_files:
  - "ml_alerts.yml"

# Scrape configurations
scrape_configs:
  # ML Prediction Server Metrics
  - job_name: 'ml-prediction-server'
    static_configs:
      - targets: ['ml-prediction-server:9090']
    metrics_path: /metrics
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ml-prediction-primary'

  # WebSocket Server Metrics
  - job_name: 'ml-websocket-server'
    static_configs:
      - targets: ['ml-websocket-server:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # MLflow Metrics
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # GPU Metrics (NVIDIA DCGM Exporter)
  - job_name: 'gpu'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Kubernetes Metrics (if deployed on K8s)
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - policycortex-ml
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 10000
#       batch_send_deadline: 5s
#       max_retries: 3