apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
  namespace: policycortex
  labels:
    app: ai-engine
    component: ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
        component: ai
    spec:
      nodeSelector:
        workload: ai
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "ai"
        effect: "NoSchedule"
      containers:
      - name: ai-engine
        image: ${ACR_NAME}.azurecr.io/policycortex-ai-engine:latest
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: ENVIRONMENT
          value: "kubernetes"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: redis-url
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: azure-openai-endpoint
        - name: AZURE_OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: azure-openai-key
        - name: AZURE_COGNITIVE_SERVICES_KEY
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: azure-cognitive-services-key
        - name: AZURE_COGNITIVE_SERVICES_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: azure-cognitive-services-endpoint
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            nvidia.com/gpu: 1
          limits:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine-service
  namespace: policycortex
  labels:
    app: ai-engine
spec:
  selector:
    app: ai-engine
  ports:
  - port: 80
    targetPort: 8002
    protocol: TCP
    name: http
  type: ClusterIP