apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-integration
  namespace: policycortex
  labels:
    app: azure-integration
    component: integration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-integration
  template:
    metadata:
      labels:
        app: azure-integration
        component: integration
    spec:
      containers:
      - name: azure-integration
        image: ${ACR_NAME}.azurecr.io/policortex001-azure-integration:latest
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: ENVIRONMENT
          value: "kubernetes"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: redis-url
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: azure-client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: azure-client-secret
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: azure-tenant-id
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: azure-subscription-id
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: azure-integration-service
  namespace: policycortex
  labels:
    app: azure-integration
spec:
  selector:
    app: azure-integration
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
  type: ClusterIP