apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation
  namespace: policycortex
  labels:
    app: conversation
    component: conversation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversation
  template:
    metadata:
      labels:
        app: conversation
        component: conversation
    spec:
      containers:
      - name: conversation
        image: ${ACR_NAME}.azurecr.io/policortex001-conversation:latest
        ports:
        - containerPort: 8004
          name: http
        env:
        - name: ENVIRONMENT
          value: "kubernetes"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: redis-url
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: azure-openai-endpoint
        - name: AZURE_OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: azure-openai-key
        - name: COSMOS_DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: policortex001-secrets
              key: cosmos-db-connection-string
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: conversation-service
  namespace: policycortex
  labels:
    app: conversation
spec:
  selector:
    app: conversation
  ports:
  - port: 80
    targetPort: 8004
    protocol: TCP
    name: http
  type: ClusterIP