apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: policycortex
  labels:
    app: notification
    component: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
        component: notification
    spec:
      containers:
      - name: notification
        image: ${ACR_NAME}.azurecr.io/policycortex-notification:latest
        ports:
        - containerPort: 8005
          name: http
        env:
        - name: ENVIRONMENT
          value: "kubernetes"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: redis-url
        - name: AZURE_COMMUNICATION_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: azure-communication-connection-string
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: sendgrid-api-key
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: twilio-account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: policycortex-secrets
              key: twilio-auth-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: policycortex
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
  - port: 80
    targetPort: 8005
    protocol: TCP
    name: http
  type: ClusterIP