name: Reusable Security Scans

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  secret-scan:
    name: Secret scanning (trufflehog)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.80.0
        with:
          path: .
          base: ${{ github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.event.pull_request.head.sha || github.sha }}
        continue-on-error: true

  dependency-review:
    name: Dependency review (PRs)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if dependency review is available
        id: check_dependency_review
        run: |
          # Dependency review requires GitHub Advanced Security on private repos
          # For now, we'll skip this on private repos without GHAS
          echo "Checking repository visibility and features..."
          if [[ "${{ github.event.repository.private }}" == "true" ]]; then
            echo "Private repository detected - dependency review may not be available"
            echo "available=false" >> $GITHUB_OUTPUT
          else
            echo "Public repository - dependency review should work"
            echo "available=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/dependency-review-action@v4
        if: steps.check_dependency_review.outputs.available == 'true'
        continue-on-error: true
      - name: Skip message
        if: steps.check_dependency_review.outputs.available == 'false'
        run: |
          echo "⚠️ Dependency review skipped for private repository"
          echo "To enable, configure GitHub Advanced Security in repository settings:"
          echo "https://github.com/${{ github.repository }}/settings/security_analysis"



