global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'gateway'
    static_configs: [{ targets: ['host.docker.internal:8000', 'localhost:8000'] }]
    metrics_path: /metrics
  - job_name: 'core'
    static_configs: [{ targets: ['host.docker.internal:8081', 'localhost:8081'] }]
    metrics_path: /metrics
  - job_name: 'agents'
    static_configs: [{ targets: ['host.docker.internal:8084', 'localhost:8084'] }]
    metrics_path: /metrics