name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    # Use this YAML in your workflow file for each job
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Update apt cache (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update -y

      - name: Setup Node.js
      # Self-hosted runner can skip if Node is preinstalled; this ensures version
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend type-check and build
        working-directory: frontend
        run: |
          npm ci
          npm run type-check
          npm run build

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust build and clippy
        working-directory: core
        run: |
          cargo build --locked
          cargo clippy -- -D warnings
          cargo test --locked --all --no-fail-fast -- --nocapture

      - name: Core unit tests (optional)
        if: ${{ false }}
        working-directory: core
        run: |
          cargo test --all --locked
