name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-secure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Supply chain security (SBOM, CVE, SLSA)
        run: |
          chmod +x scripts/supply-chain-security.sh
          ./scripts/supply-chain-security.sh

      - name: Secret scanning with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          args: detect --no-banner --redact --exit-code 1

      - name: Frontend lint
        run: |
          cd frontend
          npm ci
          npm run lint --if-present

      - name: Python lint
        run: |
          pip install ruff
          ruff check backend || true

      - name: Report status
        run: echo "CI checks completed"
