name: Deploy (Reusable)

on:
  # Allow call from entry workflow and manual runs
  workflow_call:
    inputs:
      from_tag:
        description: 'Optional semver tag to deploy'
        required: false
        type: string
  workflow_dispatch:

jobs:
  deploy:
    # Use this YAML in your workflow file for each job
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: docker compose -f docker-compose.yml build

      - name: Push images (optional)
        if: ${{ env.REGISTRY && env.REGISTRY_USER && env.REGISTRY_PASS }}
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
        run: |
          echo "$REGISTRY_PASS" | docker login "$REGISTRY" -u "$REGISTRY_USER" --password-stdin
          docker compose -f docker-compose.yml push

      - name: Deploy stack
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for services
        run: |
          set -e
          # Core exposed as 8085 externally per compose
          curl -fsS http://localhost:8085/health
          # GraphQL optional
          curl -fsS http://localhost:4001/health || true
          # Public domain over HTTPS (self-signed allowed in early stages)
          curl -kfsS https://policycortex.com/health

