name: Model evaluations

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  evals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run model registry tests
        run: |
          cd core
          cargo test -q -p policycortex-core -- ai::model_registry -- --nocapture
      - name: Gate on acceptance thresholds (example)
        run: |
          echo "Simulating threshold check..."
          # In a real setup, parse eval outputs and enforce min thresholds
