name: Model evaluations

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      run_evals:
        description: 'Run model evals (compiles Rust core)'
        required: false
        default: false
        type: boolean

jobs:
  evals:
    # Only run when manually dispatched with run_evals=true. Skips on push/PR by default.
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.run_evals == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run model registry tests
        run: |
          echo "Model evals disabled by default. Enable via workflow_dispatch input run_evals=true."
          exit 0
      - name: Gate on acceptance thresholds (example)
        run: |
          echo "Simulating threshold check..."
          # In a real setup, parse eval outputs and enforce min thresholds
