name: Project Automation

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, ready_for_review, closed]

permissions:
  contents: read
  issues: write
  pull-requests: write
  projects: write

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/laeintel/projects/1
          # Prefer a fine-grained PAT with Projects: Read/Write on the org project
          github-token: ${{ secrets.PROJECTS_TOKEN || secrets.GITHUB_TOKEN }}
          
  label-issues:
    name: Auto-label issues
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Label new issues
        uses: andymckay/labeler@master
        if: github.event.action == 'opened'
        with:
          add-labels: "needs-triage"
          
  assign-pr-author:
    name: Auto-assign PR author
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Assign PR to author
        uses: technote-space/assign-author@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}