name: Reusable Security Scans

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  secret-scan:
    name: Secret scanning (trufflehog)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.80.0
        with:
          path: .
          base: ${{ github.event.pull_request.base.sha || github.event.before }}
          head: ${{ github.event.pull_request.head.sha || github.sha }}
        continue-on-error: true

  dependency-review:
    name: Dependency review (PRs)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4


