name: Reusable Python CI

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.11'
        type: string
      working-directory:
        description: 'Working directory for Python operations'
        required: false
        default: 'backend'
        type: string

jobs:
  python-ci:
    name: Python Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            ${{ inputs.working-directory }}/requirements.txt
            ${{ inputs.working-directory }}/requirements-dev.txt
            ${{ inputs.working-directory }}/**/requirements*.txt
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install main requirements if exists
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Install dev requirements if exists
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi
          # Install test requirements if exists
          if [ -f requirements-test.txt ]; then
            pip install -r requirements-test.txt
          fi
          # Look for service-specific requirements
          for req in services/*/requirements.txt; do
            if [ -f "$req" ]; then
              echo "Installing requirements from $req"
              pip install -r "$req"
            fi
          done
      
      - name: Lint with flake8
        continue-on-error: true
        run: |
          # Install flake8 if not already installed
          pip install flake8
          # Run flake8 with reasonable defaults
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Type check with mypy
        continue-on-error: true
        run: |
          # Install mypy if not already installed
          pip install mypy
          # Run mypy on Python files
          mypy . --ignore-missing-imports --no-strict-optional || true
      
      - name: Test with pytest
        run: |
          # Install pytest if not already installed
          pip install pytest pytest-cov pytest-asyncio
          # Run tests with coverage
          pytest --verbose --cov=. --cov-report=term-missing || echo "No tests found or tests failed"
      
      - name: Security check with bandit
        continue-on-error: true
        run: |
          # Install bandit for security checks
          pip install bandit
          # Run bandit security scan
          bandit -r . -ll || true
      
      - name: Check for hardcoded secrets
        continue-on-error: true
        run: |
          # Simple check for potential hardcoded secrets
          echo "Checking for potential hardcoded secrets..."
          grep -r "password\s*=\s*[\"'][^\"']*[\"']" . --include="*.py" || echo "No hardcoded passwords found"
          grep -r "api_key\s*=\s*[\"'][^\"']*[\"']" . --include="*.py" || echo "No hardcoded API keys found"
          grep -r "secret\s*=\s*[\"'][^\"']*[\"']" . --include="*.py" || echo "No hardcoded secrets found"