name: Secret scan (gitleaks)

on:
  # Converted to reusable; called from entry workflow
  workflow_call:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks (licensed)
        if: ${{ secrets.GITLEAKS_LICENSE != '' }}
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          args: detect --source=. --no-git --redact --report-format sarif --report-path gitleaks.sarif --config=.gitleaks.toml
        continue-on-error: true
      - name: Upload SARIF to code scanning
        if: ${{ always() && secrets.GITLEAKS_LICENSE != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
