name: Secret scan (gitleaks)

on:
  # Converted to reusable; called from entry workflow
  workflow_call:
    secrets:
      GITLEAKS_LICENSE:
        required: false

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    env:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks (licensed)
        if: ${{ env.GITLEAKS_LICENSE != '' }}
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ env.GITLEAKS_LICENSE }}
        with:
          args: detect --source=. --no-git --redact --report-format sarif --report-path gitleaks.sarif
        continue-on-error: true
      - name: Check SARIF exists
        id: sarif
        run: |
          if [ -f gitleaks.sarif ]; then echo "exists=true" >> $GITHUB_OUTPUT; else echo "exists=false" >> $GITHUB_OUTPUT; fi
      - name: Upload SARIF to code scanning
        if: ${{ always() && env.GITLEAKS_LICENSE != '' && steps.sarif.outputs.exists == 'true' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
