name: Test Windows Self-Hosted Agent

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: false
        default: 'Testing aeolitech-runner1'
        type: string

jobs:
  test-agent:
    name: Test Agent
    runs-on: [self-hosted, Windows, X64, aeolitech-runner1]
    timeout-minutes: 5
    
    steps:
      - name: Basic Agent Test
        run: |
          Write-Host "Agent Test Started" -ForegroundColor Green
          Write-Host "Message: ${{ github.event.inputs.message }}" -ForegroundColor Yellow
          Write-Host "Computer: $env:COMPUTERNAME" -ForegroundColor Cyan
          Write-Host "User: $env:USERNAME" -ForegroundColor Cyan
          Write-Host "Runner: $env:RUNNER_NAME" -ForegroundColor Cyan
          Write-Host "Test Completed Successfully!" -ForegroundColor Green
        shell: powershell
        
      - name: Test File Operations
        run: |
          echo "Testing file operations"
          echo "Agent is working" > test-file.txt
          type test-file.txt
          del test-file.txt
          echo "File operations successful"
        shell: cmd
        
      - name: Test Environment
        run: |
          Write-Host "GitHub Workspace: ${{ github.workspace }}" -ForegroundColor Cyan
          Write-Host "GitHub Repository: ${{ github.repository }}" -ForegroundColor Cyan
          Write-Host "Run Number: ${{ github.run_number }}" -ForegroundColor Cyan
          Write-Host "Environment test completed" -ForegroundColor Green
        shell: powershell

  notify-result:
    name: Test Result
    runs-on: ubuntu-latest
    needs: test-agent
    if: always()
    
    steps:
      - name: Success Message
        if: needs.test-agent.result == 'success'
        run: |
          echo "✅ SUCCESS: aeolitech-runner1 is working!"
          echo "Agent can take jobs and execute tasks successfully."
          
      - name: Failure Message
        if: needs.test-agent.result != 'success'
        run: |
          echo "❌ FAILED: aeolitech-runner1 has issues"
          echo "Check the agent service and try again."